
authors = ["Chris Anderson"]
cloned_from = "mMFRCSsFePbU5ZYYCudr36"
description = "Weather App"
language = "go"
manifest_version = 3
name = "A weather project"
service_id = "mMFRCSsFePbU5ZYYCudr36"

[scripts]
env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
build = "go build -o bin/main.wasm ."
